### ISSUE TITLE
CODEOWNERES file not found

### ISSUE THREAD

**Issue by gxs-antran** [andre-alves/danger-missing_codeowners#4]
I got this error when running danger

> Invalid `Dangerfile_size_report` file: No such file or directory @ rb_sysopen - /CODEOWNERS

The CODEOWNERS and Dangerfile are both at the root of the project.

Do you have any idea what is going wrong here?

**Comment by gxs-antran** [comment]
it seems that I have to put that file into .gitlab folder to avoid the error. Is it expected?

**Comment by andre-alves** [comment]
Fixed in version 1.2.1.

Thanks for the report!
