### ISSUE TITLE
Can't parse lines without codeowners

### ISSUE THREAD

**Issue by gxs-antran** [andre-alves/danger-missing_codeowners#6]
Hi,

I'm trying to exclude files and folders from CODEOWNERS file. From [Stackoverflow](https://stackoverflow.com/a/74964396) it looks like we can list those files without code owners to ignore them from checking.

Currently, this danger task is failing with error

```
/lib/missing_codeowners/plugin.rb:138:in `block in parse_codeowners_spec':
```

Do I understand correctly that we can't ignore files with current implementation?

**Comment by andre-alves** [comment]
I didn't know this was possible. It should be easy to support it just by removing this elsif:

https://github.com/andre-alves/danger-missing_codeowners/blob/main/lib/missing_codeowners/plugin.rb#L137

I can take a look later this week.
